---
- name: Remove Allora Worker Node
  hosts: localhost
  become: true

  tasks:
    - name: Stop Allora Worker Node service
      ansible.builtin.systemd:
        name: allora-worker-node
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Wait for any remaining processes to terminate
      ansible.builtin.wait_for:
        timeout: 30

    - name: Remove Allora Worker Node service file
      ansible.builtin.file:
        path: /etc/systemd/system/allora-worker-node.service
        state: absent
      ignore_errors: true

    - name: Remove Allora Worker Node data directories
      ansible.builtin.file:
        path: "/root/basic-coin-prediction-node"
        state: absent
      ignore_errors: true

    - name: Remove Docker containers and images
      ansible.builtin.shell: |
        docker-compose -f /root/basic-coin-prediction-node/docker-compose.yml down
        docker system prune -af
      ignore_errors: true

    - name: Remove Docker Compose binary
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        state: absent
      ignore_errors: true

    - name: Reload systemd to apply changes
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl reset-failed
      ignore_errors: true

    - name: Display message
      ansible.builtin.debug:
        msg: "Allora Worker Node has been removed successfully."
